import { Component, ViewChild, inject } from '@angular/core';
import { Location } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { FormsModule, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { BusinessApiService } from '../business-api.service';
import { ModalComponent } from '../../shared/modal/modal.component';
import { ImageUploadComponent } from '../../shared/image-upload/image-upload.component';
import { BUSINESS_CATEGORIES } from '../../shared/business-category';
import { MapComponent, MapPosition } from '../../shared/map/map.component';
import { QrCodeComponent } from '../../shared/qr-code/qr-code.component';
import { OrderStatus, PaymentMethod } from '../business.models';
import { NotificationService } from '../../shared/notification.service';

const DAYS = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
const DEFAULT_POSITION: MapPosition = { lat: 19.4326, lng: -99.1332 };
type FulfillmentSettings = { pickup_enabled: boolean; delivery_enabled: boolean; dine_in_enabled: boolean; pickup_fee?: number | null; delivery_fee?: number | null; dine_in_fee?: number | null };
export function unconfiguredDays(hours: { day_of_week: number }[]): number[] { const configured = new Set(hours.map(hour => hour.day_of_week)); return DAYS.map((_, day) => day).filter(day => !configured.has(day)); }

@Component({ standalone: true, imports: [FormsModule, ReactiveFormsModule, RouterLink, ModalComponent, ImageUploadComponent, MapComponent, QrCodeComponent], styleUrl: './business-settings.component.css', templateUrl: './business-settings.component.html' })
export class BusinessSettingsComponent {
  private readonly api = inject(BusinessApiService); private readonly location = inject(Location); private readonly router = inject(Router); readonly notification = inject(NotificationService); @ViewChild(QrCodeComponent) qrCode?: QrCodeComponent; businessId = 0; publicCatalogUrl?: string; logo?: File; coverImage?: File; coverImageUrl?: string | null; mapCenter = DEFAULT_POSITION; position?: MapPosition; hoursModal = false; fulfillment: FulfillmentSettings = { pickup_enabled: true, delivery_enabled: false, dine_in_enabled: false, pickup_fee: null, delivery_fee: null, dine_in_fee: null }; paymentMethods: PaymentMethod[] = []; paymentMethodInput = ''; orderStatuses: OrderStatus[] = []; orderStatusInput = ''; orderStatusColor = '#EA580C'; orderStatusTerminal = false; hours = Array.from({ length: 7 }, (_, day) => ({ day_of_week: day, opens_at: '09:00', closes_at: '18:00', is_closed: false })); readonly dayNames = DAYS; readonly categories = BUSINESS_CATEGORIES;
  readonly profile = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: [Validators.required] }), whatsapp_number: new FormControl('', { nonNullable: true }), description: new FormControl('', { nonNullable: true }), category: new FormControl<string | null>(null), location: new FormControl('', { nonNullable: true }) });
  get publicCatalogQrUrl(): string | undefined { return this.publicCatalogUrl ? `${this.publicCatalogUrl}?src=qr` : undefined; }
  constructor() { this.api.getMine().subscribe({ next: result => { this.businessId = result.business.id; this.publicCatalogUrl = this.businessId && result.business.slug ? window.location.origin + this.location.prepareExternalUrl(this.router.serializeUrl(this.router.createUrlTree(['/public/catalog', result.business.slug]))) : undefined; this.coverImageUrl = result.business.cover_image_url; this.fulfillment = { pickup_enabled: result.business.pickup_enabled ?? true, delivery_enabled: result.business.delivery_enabled ?? false, pickup_fee: result.business.pickup_fee == null ? null : Number(result.business.pickup_fee), delivery_fee: result.business.delivery_fee == null ? null : Number(result.business.delivery_fee), dine_in_enabled: result.business.dine_in_enabled ?? false, dine_in_fee: result.business.dine_in_fee == null ? null : Number(result.business.dine_in_fee) }; this.paymentMethods = [...(result.business.payment_methods ?? [])].sort((a, b) => a.position - b.position); this.orderStatuses = [...(result.business.order_statuses ?? [])].sort((a, b) => a.position - b.position); if (result.business.latitude != null && result.business.longitude != null) { this.position = { lat: result.business.latitude, lng: result.business.longitude }; this.mapCenter = this.position; } this.profile.patchValue({ name: result.business.name, whatsapp_number: result.business.whatsapp_number ?? '', description: result.business.description ?? '', category: result.business.category ?? null, location: result.business.location ?? '' }); for (const saved of result.hours) Object.assign(this.hours[saved.day_of_week], saved); }, error: () => { this.businessId = 0; this.publicCatalogUrl = undefined; } }); }
  downloadQr(): void { this.qrCode?.download('catalogo-qr.png'); }
  enabledCount(): number { return [this.fulfillment.pickup_enabled, this.fulfillment.delivery_enabled, this.fulfillment.dine_in_enabled].filter(Boolean).length; }
  saveProfile(): void { if (this.profile.invalid || !this.businessId || !this.enabledCount()) { this.notification.error('Mantén al menos un método habilitado.'); return; } const fields = { ...this.profile.getRawValue(), ...this.fulfillment, pickup_fee: this.fee(this.fulfillment.pickup_fee), delivery_fee: this.fee(this.fulfillment.delivery_fee), dine_in_fee: this.fee(this.fulfillment.dine_in_fee), latitude: this.position?.lat ?? null, longitude: this.position?.lng ?? null }; this.api.update(this.businessId, fields, this.logo, this.coverImage).subscribe({ next: () => this.notification.success('Perfil guardado con éxito.'), error: response => this.notification.error(response.error?.error ?? 'No se pudo guardar el perfil.') }); }
  fee(value?: number | null): number | null { const number = Number(value); return Number.isFinite(number) && number >= 0 ? number : null; }
  addPaymentMethod(): void { const name = this.paymentMethodInput.trim(); if (!name || !this.businessId) return; this.api.addPaymentMethod(this.businessId, name).subscribe({ next: method => { this.paymentMethods = [...this.paymentMethods, method]; this.paymentMethodInput = ''; }, error: response => this.notification.error(response.error?.error ?? 'No se pudo agregar el método de pago.') }); }
  renamePaymentMethod(method: PaymentMethod): void { const name = method.name.trim(); if (!name || !this.businessId) return; this.api.renamePaymentMethod(this.businessId, method.id, name).subscribe({ next: saved => Object.assign(method, saved), error: response => this.notification.error(response.error?.error ?? 'No se pudo renombrar el método de pago.') }); }
  deletePaymentMethod(method: PaymentMethod): void { if (this.paymentMethods.length === 1 || !this.businessId) return; this.api.deletePaymentMethod(this.businessId, method.id).subscribe({ next: () => this.paymentMethods = this.paymentMethods.filter(item => item.id !== method.id), error: response => this.notification.error(response.error?.error ?? 'No se pudo eliminar el método de pago.') }); }
  movePaymentMethod(method: PaymentMethod, direction: -1 | 1): void { const index = this.paymentMethods.indexOf(method); const next = index + direction; if (next < 0 || next >= this.paymentMethods.length || !this.businessId) return; [this.paymentMethods[index], this.paymentMethods[next]] = [this.paymentMethods[next], this.paymentMethods[index]]; this.api.reorderPaymentMethods(this.businessId, this.paymentMethods.map(item => item.id)).subscribe({ error: response => this.notification.error(response.error?.error ?? 'No se pudo reordenar los métodos de pago.') }); }
  addOrderStatus(): void { const name = this.orderStatusInput.trim(); if (!name || !this.businessId) return; this.api.addOrderStatus(this.businessId, name, this.orderStatusColor, this.orderStatusTerminal).subscribe({ next: status => { this.orderStatuses = [...this.orderStatuses, status]; this.orderStatusInput = ''; }, error: response => this.notification.error(response.error?.error ?? 'No se pudo agregar el estado del pedido.') }); }
  renameOrderStatus(status: OrderStatus): void { const name = status.name.trim(); if (!name || !this.businessId) return; this.api.renameOrderStatus(this.businessId, status.id, name).subscribe({ next: saved => Object.assign(status, saved), error: response => this.notification.error(response.error?.error ?? 'No se pudo renombrar el estado del pedido.') }); }
  recolorOrderStatus(status: OrderStatus): void { if (!this.businessId) return; this.api.recolorOrderStatus(this.businessId, status.id, status.color).subscribe({ next: saved => Object.assign(status, saved), error: response => this.notification.error(response.error?.error ?? 'No se pudo cambiar el color del estado.') }); }
  toggleOrderStatusTerminal(status: OrderStatus): void { if (!this.businessId) return; this.api.setOrderStatusTerminal(this.businessId, status.id, status.is_terminal).subscribe({ next: saved => Object.assign(status, saved), error: response => this.notification.error(response.error?.error ?? 'No se pudo actualizar el estado terminal.') }); }
  setDefaultOrderStatus(status: OrderStatus): void { if (!this.businessId || status.is_default) return; this.api.setOrderStatusDefault(this.businessId, status.id).subscribe({ next: saved => { this.orderStatuses.forEach(item => item.is_default = item.id === status.id); Object.assign(status, saved, { is_default: true }); }, error: response => this.notification.error(response.error?.error ?? 'No se pudo establecer el estado predeterminado.') }); }
  deleteOrderStatus(status: OrderStatus): void { if (this.orderStatuses.length === 1 || status.is_default || !this.businessId) return; this.api.deleteOrderStatus(this.businessId, status.id).subscribe({ next: () => this.orderStatuses = this.orderStatuses.filter(item => item.id !== status.id), error: response => this.notification.error(response.error?.error ?? 'No se pudo eliminar el estado del pedido.') }); }
  moveOrderStatus(status: OrderStatus, direction: -1 | 1): void { const index = this.orderStatuses.indexOf(status); const next = index + direction; if (next < 0 || next >= this.orderStatuses.length || !this.businessId) return; [this.orderStatuses[index], this.orderStatuses[next]] = [this.orderStatuses[next], this.orderStatuses[index]]; this.api.reorderOrderStatuses(this.businessId, this.orderStatuses.map(item => item.id)).subscribe({ error: response => this.notification.error(response.error?.error ?? 'No se pudo reordenar los estados del pedido.') }); }
  onLogoSelected(file: File): void { this.logo = file; }
  onCoverSelected(file: File): void { this.coverImage = file; }
  onPositionChanged(position: MapPosition): void { this.position = position; this.mapCenter = position; }
  saveHours(): void { if (this.businessId) this.api.saveHours(this.businessId, this.hours).subscribe(() => this.hoursModal = false); }
}
