import { CatalogManagementComponent, hasInvalidPricedOptions } from './catalog-management.component';
import { NotificationService } from '../../shared/notification.service';
import { of, throwError } from 'rxjs';

describe('catalog option editing', () => {
  function component(): CatalogManagementComponent { const instance = Object.create(CatalogManagementComponent.prototype) as CatalogManagementComponent; instance.product = { category_id: 1, name: 'Cafe', options: [] }; return instance; }
  it('adds a group and a value with a price delta', () => { const instance = component(); instance.addOption(); instance.addOptionValue(instance.product.options![0]); instance.product.options![0].values[0].price_delta = 15; expect(instance.product.options![0].values[0].price_delta).toBe(15); });
  it('guards priced options on a priceless product', () => { const instance = component(); instance.addOption(); instance.addOptionValue(instance.product.options![0]); instance.product.options![0].values[0].price_delta = 15; expect(hasInvalidPricedOptions(instance.product)).toBeTrue(); });
  it('keeps priced-option validation inline without a notification', () => { const instance = component(); const notification = jasmine.createSpyObj<NotificationService>('NotificationService', ['success', 'error']); const internals = instance as unknown as { notification: NotificationService; productsApi: { create: jasmine.Spy } }; internals.notification = notification; internals.productsApi = { create: jasmine.createSpy().and.returnValue(of({})) }; instance.product = { category_id: 1, name: 'Cafe', price: null, options: [{ name: 'Extras', selection_type: 'single', required: false, values: [{ name: 'Queso', price_delta: 15 }] }] }; instance.businessId = 1; instance.saveProduct(); expect(instance.productError).toBe('Los extras con precio requieren un producto con precio.'); expect(notification.error).not.toHaveBeenCalled(); });
  it('notifies for the coordinates guard and publish failures', () => { const instance = component(); const notification = jasmine.createSpyObj<NotificationService>('NotificationService', ['success', 'error']); const internals = instance as unknown as { notification: NotificationService; businessApi: { publish: jasmine.Spy } }; internals.notification = notification; instance.published = false; instance.hasCoordinates = false; instance.togglePublish(); expect(notification.error).toHaveBeenCalledWith(instance.coordinatesRequiredMessage); instance.hasCoordinates = true; internals.businessApi = { publish: jasmine.createSpy().and.returnValue(throwError(() => ({ error: 'Set a location on the map before publishing.' }))) }; instance.togglePublish(); expect(notification.error).toHaveBeenCalledWith(instance.coordinatesRequiredMessage); internals.businessApi.publish.and.returnValue(throwError(() => new Error('failed'))); instance.togglePublish(); expect(notification.error).toHaveBeenCalledWith('No se pudo actualizar la publicación del catálogo.'); });
});
